### ISSUE TITLE
Refresh method is the most stupid thing I have seen in a while.

### ISSUE THREAD

**Issue by saketramdurbha** [mathnerdrk/To-Do#1]
Why the actual fuck are we making a new window and hiding the current one every time we want to fucking refresh the frame?

**Comment by mathnerdrk** [comment]
ok i just did the quickest thing i could think of and plus its only temporary we will take it out once we figure out what is going on with the windows not appearing properly

**Comment by mathnerdrk** [comment]
There I changed it to this.dispose() instead of this.setVisible(false);
